public class OpportunityClass {
    public void opportunityMethod(){
        String[] name = new List<String>{'Rishabh','shivam',
    'Rajat','nishchal','Shubham'}; 
          integer[] day = new List<integer>{2,4,5,4,2};
            integer[] month = new List<integer>{05,02,04,03,08};
                integer[] year = new List<integer>{2010,2011,2012,2013,2014};
      
    date[] dt = new List<date>();
        
          dt[0]= date.newInstance(year[0], month[0],day[0]);
            System.debug('date'+dt[0]);
        
   
    }
    
}